# Generated by Django 4.0.6 on 2022-07-25 13:13

import click_and_eat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressOfRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('longitude', models.FloatField(default='1')),
                ('latitude', models.FloatField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('icon', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=8)),
                ('secret_code', models.CharField(max_length=8)),
                ('comment', models.CharField(default=None, max_length=512, null=True)),
                ('order_time', models.DateTimeField()),
                ('pickup_time', models.DateTimeField(null=True)),
                ('order_finish_time', models.DateTimeField(null=True)),
                ('finished', models.BooleanField()),
                ('instant', models.BooleanField()),
                ('canceled', models.BooleanField()),
                ('cancel_reason', models.CharField(default=None, max_length=512, null=True)),
                ('in_progress', models.BooleanField()),
                ('ready', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='click_and_eat.addressofrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('logo', models.ImageField(upload_to=click_and_eat.models.restaurant_data_directory_path)),
                ('preview_image', models.ImageField(upload_to=click_and_eat.models.restaurant_data_directory_path)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('categories', models.ManyToManyField(related_name='provider', to='click_and_eat.restaurantcategory')),
                ('main_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='click_and_eat.restaurantcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.ManyToManyField(blank=True, to='click_and_eat.allergy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('photo', models.ImageField(null=True, upload_to=click_and_eat.models.product_directory_path)),
                ('description', models.CharField(default='', max_length=1024)),
                ('price', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=16)),
                ('allergies', models.ManyToManyField(blank=True, to='click_and_eat.allergy')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='click_and_eat.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='click_and_eat.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='click_and_eat.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='click_and_eat.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='click_and_eat.restaurant'),
        ),
        migrations.AddField(
            model_name='addressofrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='click_and_eat.restaurant'),
        ),
    ]
