# Generated by Django 3.0.5 on 2020-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=1024),
        ),
    ]
